#!/bin/bash
set -e

# Install dependencies
npm i

# Run Next app
npm run dev &

# Pause script and allow server to start before running next command
sleep 5

# Open localhost server (port 3000)
open http://localhost:3000