#!/bin/bash
set -e

# Run Next app
npm run dev &

# Pause script (5 seconds) and allow local server to start before running final command
sleep 5

# Open localhost server (port 3000)
open http://localhost:3000